services:
  backend:
    container_name: backend
    build: ./kreftregisteret-backend
    ports:
      - 8080:8080
    volumes:
      - ./kreftregisteret-backend:/app/kreftregisteret-backend
  frontend:
    container_name: frontend
    build: ./kreftregisteret-frontend
    ports:
      - 3000:3000

