name: Build static react build in resources
on:
  push:
    branches:
      - main
    paths:
      - 'kreftregisteret-frontend/**'
jobs:
  react-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Make static react build
        working-directory: ./kreftregisteret-frontend
        run: |
          npm ci
          npm run build

      - name: Copy to resources
        run: |
          chmod +x ./mv_build_to_resources.sh
          ./mv_build_to_resources.sh
        shell: bash

      - name: Commit and push static build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f ./kreftregisteret-backend/src/main/resources/static
          git commit -m "🤖 Generated static build"
          git push
