name: Build and run Maven tests
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run all tests with Maven
        working-directory: ./kreftregisteret-backend
        run: ./mvnw clean test
